sudo: required

services:
  -docker
  
language: python

before_install:
  - echo "=============================="
  - echo "Before Install"
  - echo "=============================="
  - uname -a
  - python --version
  - docker pull laszewski/cloudmesh-tex:0.0.1


script:
  - echo "=============================="
  - echo "Scripts"
  - echo "=============================="
  - docker run laszewski/cloudmesh-tex:0.0.1 /bin/sh -c "cd /book; make pdflatex"
  - docker run laszewski/cloudmesh-tex:0.0.1 /bin/sh -c "cd /book; ls"
  - docker run laszewski/cloudmesh-tex:0.0.1 /bin/sh -c "cd /book; ls; pdflatex vonLaszewski-bigdata.tex; ls;"